server:
  port: 8082

spring:
  application:
    name: "custom-configure-client-two"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/



management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
    health:
      show-details: always


info:
  application:
    name: "custom-configure-client-one"
    server:
      port: 8762
  eureka:
    server: "custom-configure-eureka-server"

db:
  name: "MySQL"
  engine: "MySQLInnoDB"
  url: "jdbc:mysql://localhost:3306/your_database_name"
  username: "your_username"
  password: "your_password"
  driver-class-name: "com.mysql.cj.jdbc.Driver"

mobile:
  brandOne: "Samsung"
  brandTwo: "Lenovo"
  brandThree: "Apple"

